<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.0.0-skeleton</Version>
    <RootNamespace>RgHello.Rasterizer</RootNamespace>
    <IsPackable>false</IsPackable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="cli/**" />
    <Compile Remove="rasterizer.Tests/**" />
  </ItemGroup>

</Project>
