AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - vendor/**/*

Metrics/ParameterLists:
  Max: 8

Naming/VariableNumber:
  Exclude:
    - 'test/**/*'

Layout/LineLength:
  Max: 120
  AllowCopDirectives: true

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 20

Metrics/BlockLength:
  Max: 40

Metrics/BlockNesting:
  Max: 5

Lint/EmptyConditionalBody:
  Exclude:
    - 'lib/**/*'
