# frozen_string_literal: true

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
end

desc 'Run tests with coverage and enforce the 90% minimum'
task :coverage do
  ruby '-Ilib', '-Itest', '-rsimplecov', 'test/adjudicator_test.rb'
end

task default: :test
