apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-orchestrator
  namespace: rube-goldberg
  labels:
    app: run-orchestrator
    milestone: "6"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: run-orchestrator
  template:
    metadata:
      labels:
        app: run-orchestrator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: orchestrator
          image: rghello-registry:5001/run-orchestrator:milestone6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka.rube-goldberg.svc.cluster.local:9092
            - name: REDIS_URL
              value: redis://:RedisPassw0rd!@redis-master.rube-goldberg.svc.cluster.local:6379
            - name: ORCHESTRATOR_PORT
              value: "8080"
            - name: GLYPH_CATALOG_URL
              value: http://glyph-catalog.rube-goldberg.svc.cluster.local:8080/ws/glyph-catalog
            - name: MINIO_ENDPOINT
              value: http://minio.rube-goldberg.svc.cluster.local:9000
            - name: MINIO_BUCKET
              value: rube-goldberg-artifacts
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-password
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
