# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.4.0'

gem 'minitest', '6.0.6'
gem 'rake', '13.4.2'
gem 'rubocop', '1.89.0'
gem 'simplecov', '1.0.3'
gem 'sinatra', '4.2.0'
gem 'opentelemetry-sdk', '1.13.0'
gem 'opentelemetry-exporter-otlp', '0.34.1'
gem 'opentelemetry-instrumentation-all', '0.95.0'
gem 'opentelemetry-logs-sdk', '0.6.1'
gem 'opentelemetry-exporter-otlp-logs', '0.5.1'
