// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rasterizer/v1/rasterizer.proto

package rasterproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderGlyphRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepId          string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	GlyphInstanceId string                 `protobuf:"bytes,3,opt,name=glyph_instance_id,json=glyphInstanceId,proto3" json:"glyph_instance_id,omitempty"`
	Position        int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Attempt         int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Canvas          *Canvas                `protobuf:"bytes,6,opt,name=canvas,proto3" json:"canvas,omitempty"`
	Profile         *RenderProfile         `protobuf:"bytes,7,opt,name=profile,proto3" json:"profile,omitempty"`
	Segments        []*Segment             `protobuf:"bytes,8,rep,name=segments,proto3" json:"segments,omitempty"`
	TraceContext    *TraceContext          `protobuf:"bytes,9,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	// SHA-256 of the input normalized artifact; the idempotency input hash
	// for the section 13.5 operation ID embedded in artifact object keys.
	InputArtifactSha256 string `protobuf:"bytes,10,opt,name=input_artifact_sha256,json=inputArtifactSha256,proto3" json:"input_artifact_sha256,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RenderGlyphRequest) Reset() {
	*x = RenderGlyphRequest{}
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderGlyphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderGlyphRequest) ProtoMessage() {}

func (x *RenderGlyphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderGlyphRequest.ProtoReflect.Descriptor instead.
func (*RenderGlyphRequest) Descriptor() ([]byte, []int) {
	return file_rasterizer_v1_rasterizer_proto_rawDescGZIP(), []int{0}
}

func (x *RenderGlyphRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RenderGlyphRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *RenderGlyphRequest) GetGlyphInstanceId() string {
	if x != nil {
		return x.GlyphInstanceId
	}
	return ""
}

func (x *RenderGlyphRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RenderGlyphRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RenderGlyphRequest) GetCanvas() *Canvas {
	if x != nil {
		return x.Canvas
	}
	return nil
}

func (x *RenderGlyphRequest) GetProfile() *RenderProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *RenderGlyphRequest) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *RenderGlyphRequest) GetTraceContext() *TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

func (x *RenderGlyphRequest) GetInputArtifactSha256() string {
	if x != nil {
		return x.InputArtifactSha256
	}
	return ""
}

type Canvas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Baseline      float64                `protobuf:"fixed64,3,opt,name=baseline,proto3" json:"baseline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Canvas) Reset() {
	*x = Canvas{}
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Canvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Canvas) ProtoMessage() {}

func (x *Canvas) ProtoReflect() protoreflect.Message {
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Canvas.ProtoReflect.Descriptor instead.
func (*Canvas) Descriptor() ([]byte, []int) {
	return file_rasterizer_v1_rasterizer_proto_rawDescGZIP(), []int{1}
}

func (x *Canvas) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Canvas) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Canvas) GetBaseline() float64 {
	if x != nil {
		return x.Baseline
	}
	return 0
}

type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float64                `protobuf:"fixed64,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float64                `protobuf:"fixed64,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float64                `protobuf:"fixed64,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float64                `protobuf:"fixed64,4,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_rasterizer_v1_rasterizer_proto_rawDescGZIP(), []int{2}
}

func (x *Segment) GetX1() float64 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Segment) GetY1() float64 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Segment) GetX2() float64 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Segment) GetY2() float64 {
	if x != nil {
		return x.Y2
	}
	return 0
}

type RenderProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrokeWidth   float64                `protobuf:"fixed64,1,opt,name=stroke_width,json=strokeWidth,proto3" json:"stroke_width,omitempty"`
	Antialias     bool                   `protobuf:"varint,2,opt,name=antialias,proto3" json:"antialias,omitempty"`
	LineCap       string                 `protobuf:"bytes,3,opt,name=line_cap,json=lineCap,proto3" json:"line_cap,omitempty"`
	Supersampling uint32                 `protobuf:"varint,4,opt,name=supersampling,proto3" json:"supersampling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderProfile) Reset() {
	*x = RenderProfile{}
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderProfile) ProtoMessage() {}

func (x *RenderProfile) ProtoReflect() protoreflect.Message {
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderProfile.ProtoReflect.Descriptor instead.
func (*RenderProfile) Descriptor() ([]byte, []int) {
	return file_rasterizer_v1_rasterizer_proto_rawDescGZIP(), []int{3}
}

func (x *RenderProfile) GetStrokeWidth() float64 {
	if x != nil {
		return x.StrokeWidth
	}
	return 0
}

func (x *RenderProfile) GetAntialias() bool {
	if x != nil {
		return x.Antialias
	}
	return false
}

func (x *RenderProfile) GetLineCap() string {
	if x != nil {
		return x.LineCap
	}
	return ""
}

func (x *RenderProfile) GetSupersampling() uint32 {
	if x != nil {
		return x.Supersampling
	}
	return 0
}

type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traceparent   string                 `protobuf:"bytes,1,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate    string                 `protobuf:"bytes,2,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_rasterizer_v1_rasterizer_proto_rawDescGZIP(), []int{4}
}

func (x *TraceContext) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *TraceContext) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

type RenderGlyphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	ByteCount     uint64                 `protobuf:"varint,6,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	ContentType   string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderGlyphResponse) Reset() {
	*x = RenderGlyphResponse{}
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderGlyphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderGlyphResponse) ProtoMessage() {}

func (x *RenderGlyphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rasterizer_v1_rasterizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderGlyphResponse.ProtoReflect.Descriptor instead.
func (*RenderGlyphResponse) Descriptor() ([]byte, []int) {
	return file_rasterizer_v1_rasterizer_proto_rawDescGZIP(), []int{5}
}

func (x *RenderGlyphResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *RenderGlyphResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *RenderGlyphResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *RenderGlyphResponse) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RenderGlyphResponse) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RenderGlyphResponse) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

func (x *RenderGlyphResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_rasterizer_v1_rasterizer_proto protoreflect.FileDescriptor

const file_rasterizer_v1_rasterizer_proto_rawDesc = "" +
	"\n" +
	"\x1erasterizer/v1/rasterizer.proto\x12\x10rg.rasterizer.v1\"\xc3\x03\n" +
	"\x12RenderGlyphRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12*\n" +
	"\x11glyph_instance_id\x18\x03 \x01(\tR\x0fglyphInstanceId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x120\n" +
	"\x06canvas\x18\x06 \x01(\v2\x18.rg.rasterizer.v1.CanvasR\x06canvas\x129\n" +
	"\aprofile\x18\a \x01(\v2\x1f.rg.rasterizer.v1.RenderProfileR\aprofile\x125\n" +
	"\bsegments\x18\b \x03(\v2\x19.rg.rasterizer.v1.SegmentR\bsegments\x12C\n" +
	"\rtrace_context\x18\t \x01(\v2\x1e.rg.rasterizer.v1.TraceContextR\ftraceContext\x122\n" +
	"\x15input_artifact_sha256\x18\n" +
	" \x01(\tR\x13inputArtifactSha256\"R\n" +
	"\x06Canvas\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x1a\n" +
	"\bbaseline\x18\x03 \x01(\x01R\bbaseline\"I\n" +
	"\aSegment\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x01R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x01R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x01R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x01R\x02y2\"\x91\x01\n" +
	"\rRenderProfile\x12!\n" +
	"\fstroke_width\x18\x01 \x01(\x01R\vstrokeWidth\x12\x1c\n" +
	"\tantialias\x18\x02 \x01(\bR\tantialias\x12\x19\n" +
	"\bline_cap\x18\x03 \x01(\tR\alineCap\x12$\n" +
	"\rsupersampling\x18\x04 \x01(\rR\rsupersampling\"P\n" +
	"\fTraceContext\x12 \n" +
	"\vtraceparent\x18\x01 \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\x02 \x01(\tR\n" +
	"tracestate\"\xdd\x01\n" +
	"\x13RenderGlyphResponse\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x06 \x01(\x04R\tbyteCount\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType2h\n" +
	"\n" +
	"Rasterizer\x12Z\n" +
	"\vRenderGlyph\x12$.rg.rasterizer.v1.RenderGlyphRequest\x1a%.rg.rasterizer.v1.RenderGlyphResponseBj\n" +
	"\x16dev.rghw.rasterizer.v1Z;rghw.dev/vector-normalizer/internal/rasterproto;rasterproto\xaa\x02\x12Rghw.Rasterizer.V1b\x06proto3"

var (
	file_rasterizer_v1_rasterizer_proto_rawDescOnce sync.Once
	file_rasterizer_v1_rasterizer_proto_rawDescData []byte
)

func file_rasterizer_v1_rasterizer_proto_rawDescGZIP() []byte {
	file_rasterizer_v1_rasterizer_proto_rawDescOnce.Do(func() {
		file_rasterizer_v1_rasterizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rasterizer_v1_rasterizer_proto_rawDesc), len(file_rasterizer_v1_rasterizer_proto_rawDesc)))
	})
	return file_rasterizer_v1_rasterizer_proto_rawDescData
}

var file_rasterizer_v1_rasterizer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rasterizer_v1_rasterizer_proto_goTypes = []any{
	(*RenderGlyphRequest)(nil),  // 0: rg.rasterizer.v1.RenderGlyphRequest
	(*Canvas)(nil),              // 1: rg.rasterizer.v1.Canvas
	(*Segment)(nil),             // 2: rg.rasterizer.v1.Segment
	(*RenderProfile)(nil),       // 3: rg.rasterizer.v1.RenderProfile
	(*TraceContext)(nil),        // 4: rg.rasterizer.v1.TraceContext
	(*RenderGlyphResponse)(nil), // 5: rg.rasterizer.v1.RenderGlyphResponse
}
var file_rasterizer_v1_rasterizer_proto_depIdxs = []int32{
	1, // 0: rg.rasterizer.v1.RenderGlyphRequest.canvas:type_name -> rg.rasterizer.v1.Canvas
	3, // 1: rg.rasterizer.v1.RenderGlyphRequest.profile:type_name -> rg.rasterizer.v1.RenderProfile
	2, // 2: rg.rasterizer.v1.RenderGlyphRequest.segments:type_name -> rg.rasterizer.v1.Segment
	4, // 3: rg.rasterizer.v1.RenderGlyphRequest.trace_context:type_name -> rg.rasterizer.v1.TraceContext
	0, // 4: rg.rasterizer.v1.Rasterizer.RenderGlyph:input_type -> rg.rasterizer.v1.RenderGlyphRequest
	5, // 5: rg.rasterizer.v1.Rasterizer.RenderGlyph:output_type -> rg.rasterizer.v1.RenderGlyphResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rasterizer_v1_rasterizer_proto_init() }
func file_rasterizer_v1_rasterizer_proto_init() {
	if File_rasterizer_v1_rasterizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rasterizer_v1_rasterizer_proto_rawDesc), len(file_rasterizer_v1_rasterizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rasterizer_v1_rasterizer_proto_goTypes,
		DependencyIndexes: file_rasterizer_v1_rasterizer_proto_depIdxs,
		MessageInfos:      file_rasterizer_v1_rasterizer_proto_msgTypes,
	}.Build()
	File_rasterizer_v1_rasterizer_proto = out.File
	file_rasterizer_v1_rasterizer_proto_goTypes = nil
	file_rasterizer_v1_rasterizer_proto_depIdxs = nil
}
