apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: rube-goldberg
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: '-5m'
            spanEndTimeShift: '5m'
            filterBySpanID: false
            customQuery: false
          nodeGraph:
            enabled: true
          serviceMap:
            enabled: true
            datasourceUid: prometheus
      - name: Tempo-Search
        type: tempo
        access: proxy
        url: http://tempo:3200
        jsonData:
          nodeGraph:
            enabled: true
          serviceMap:
            enabled: true
            datasourceUid: prometheus
  dashboard.yml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
